/home/terbinos/Documents/try/.venv/bin/python: can't open file '/home/terbinos/Documents/try/keylogger.py': [Errno 2] No such file or directory
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb03b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0c80>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb15b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1e50>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1340>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0a70>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2060>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb29c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3410>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2720>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb20f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0800>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb38f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff82f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0e00>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1010>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0230>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2720>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff82c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b8c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2600>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0140>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb14c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3b60>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8e90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb38c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0aa0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0110>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172a0fe90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8680>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2180>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb09e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3740>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3c20>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8680>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb01d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3890>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1580>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb20c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b980>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8590>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0e90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0b30>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb11f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3d70>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8080>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1c70>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb11f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2930>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3950>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8b90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172a0fe90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0c80>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb07a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb39e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1a30>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff98b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb09e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0a10>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0aa0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2990>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb31d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b4a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb35c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb20c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3bf0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0e00>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1d30>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1160>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0a70>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0170>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2e40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2cf0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3080>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb27b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1130>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3e90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b890>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8ec0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb14c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0f80>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2900>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2f90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff9280>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb32f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb02f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb03e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb15b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0920>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172a0fe90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb09b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2930>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3170>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1850>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8080>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1820>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2ea0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3590>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3c20>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0980>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb23c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb04d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1460>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3410>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2d50>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8d40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb26f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb37a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2840>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3950>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff9940>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3ad0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0530>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2780>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2ea0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2f60>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff9580>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3410>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0710>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0b90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0ce0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8f20>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b860>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb14c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2630>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0380>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb02f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172b075f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb05f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb25a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2930>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0bf0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1c40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172b202f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1a00>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0f80>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb30e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1820>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0173a389b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2e10>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2c00>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb02c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3d70>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3260>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb22a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0110>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2a50>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb25d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb26f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0680>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3290>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2030>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb02c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01729a48c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff88c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3d40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0140>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1820>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2420>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172ab74a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2cc0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1a60>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb06b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb23c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3bc0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172b079e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb12b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2c00>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb07d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2de0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8b30>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb19d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1fd0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3770>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1790>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3e60>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb39e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1550>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3590>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1970>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3a40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8aa0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3800>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0fb0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3830>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2270>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01729a6540>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b980>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3b90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0620>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3440>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0ec0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2a20>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3140>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2720>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1310>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3b90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb28a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b680>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3bf0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb03e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3740>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2ff0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01729db6b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb28d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2c90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2270>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2ed0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0e90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01733f4920>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0ad0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb37a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0770>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0260>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172b202f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3ec0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1310>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb37d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1dc0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1760>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3aa0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0a10>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2030>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2900>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3f80>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b4d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0aa0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb14c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb03e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0c50>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8380>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb18e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0530>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2300>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb09e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017297c3b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b890>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb25d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3590>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2600>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb38f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172a0fe90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2f30>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb04d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3830>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3170>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8ec0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3770>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb09e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3290>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2840>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1af0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b740>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3f20>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3bf0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0b00>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb23f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3950>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0aa0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1430>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2c60>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0ad0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0fe0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b740>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2990>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3740>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3ad0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb11f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8ec0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2c90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0770>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0ad0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1400>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b7d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017297caa0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3a40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb11c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0bf0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb28d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172ab4740>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1700>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3710>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2960>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb32c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff93d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017297caa0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1970>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0cb0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0140>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb15b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01729db6b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3bf0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2420>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb13d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3680>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff92e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb08f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3ec0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1520>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb28d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172b075c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2ea0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1130>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2c00>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3740>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1280>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff9490>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0ad0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb37d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb30e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0ec0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171ff8e60>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb25a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb15b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3e90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1220>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b5c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b9b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1100>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3a70>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2c90>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2060>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1fd0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b740>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e090>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369eb40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f620>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172ab41d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e360>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0173672480>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3560>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3710>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01729db6b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e030>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e510>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f620>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0e00>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f560>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e780>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369dd30>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01729a48c0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb34d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172ab4170>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e300>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369ddf0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f050>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3650>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb03e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e9f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f1d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369db20>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0173672300>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3290>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b4a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369df40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e720>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f620>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0dd0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369ee10>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f050>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369dd30>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0173672270>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1dc0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0c50>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017360eba0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369dd30>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f050>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f260>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2270>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369ef00>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369ecc0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369dd60>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b830>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1d00>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172b075f0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01734ec170>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369dcd0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e720>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb33e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2db0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369eb70>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369df40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0173790980>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172ab4440>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3650>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b740>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e360>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369ee40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e000>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3fe0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e960>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369dc40>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f530>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017360eba0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0230>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2930>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0173a6dac0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f4d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369ed80>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f170>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2f30>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f1a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e8a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369d9a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01729a6540>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2270>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb3530>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0172ab4440>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369eae0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e5a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f0b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb0800>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f650>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e8a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e450>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01736712b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2a80>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171f4b9e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01733f4920>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369e630>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f7d0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb39e0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1040>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f380>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f4a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f530>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017297caa0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb2fc0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d01729db6b0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369ea20>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369dcd0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f110>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb04a0>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d0171fb1550>: Failed to establish a new connection: [Errno 113] No route to host'))
Error sending log: HTTPConnectionPool(host='192.168.1.5', port=5000): Max retries exceeded with url: /send_log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7d017369f320>: Failed to establish a new connection: [Errno 113] No route to host'))
